sudo: required
services:
  - docker

before_install:
  - docker build -t johnmurray/docker-react2 -f Dockerfile.dev .

script:
  - docker run  -e CI=true johnmurray/docker-react2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-992382767942"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_Access_key: "$AWS_SECRET_KEY"
  


